services:
  - type: web
    name: puppeteer-lite
    env: node
    buildCommand: |
      npm install
      apt-get update && apt-get install -y chromium
    startCommand: node index.js
    plan: free
    envVars:
      - key: PORT
        value: "10000"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/chromium"
      - key: NODE_ENV
        value: "production"