services:
  - type: web
    name: puppeteer-simple
    env: node
    buildCommand: |
      npm install
      apt-get update && apt-get install -y chromium
    startCommand: node index.js
    plan: free
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/chromium"