services:
  - type: web
    name: puppeteer-latest
    env: node
    buildCommand: |
      npm install
      apt-get update && apt-get install -y chromium
    startCommand: node index.js
    plan: standard # حداقل 1GB RAM
    nodeVersion: 20.18.1