services:
  - type: web
    name: puppeteer-app
    env: node
    buildCommand: |
      npm install
      apt-get update && apt-get install -y chromium
    startCommand: npm start
    plan: free # یا standard